version: '3.8'

services:
  web:
    build: .
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/postcards.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app:z
      - postcards_data:/app/static/postcards
      - images_data:/app/static/images
    depends_on:
      - redis

  caddy:
    image: caddy:latest
    ports:
      - "5000:5000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z
    depends_on:
      - web

  app:
    build:
      context: ./rayonPushling
      dockerfile: Dockerfile
    ports:
      - "31337:31337"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - redis
    volumes:
      - ./rayonPushling/xinetd.conf:/etc/xinetd.d/mail_panda:z

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --port 6379
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - redis_data:/data

volumes:
  postcards_data:
  images_data:
  redis_data:
