version: "3"
services:
  redpanda:
    image: redpanda-custom
    container_name: redpanda-1
    ports:
      - "9092:9092"
    environment:
      - REDPANDA_ADVERTISED_KAFKA_API=localhost:9092  # Настраиваем Redpanda для работы локально
    volumes:
      - redpanda_redpanda-data:/var/lib/redpanda/data
volumes:
  redpanda_redpanda-data:
